export const REQUEST_START = 'REQUEST_START'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_END = 'REQUEST_END'

export const FETCH_TOPICS = 'FETCH_TOPICS'
export const FETCH_TOPIC_DETAIL = 'FETCH_TOPIC_DETAIL'
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'

export const SAVE_COLLECT = 'SAVE_COLLECT'
export const DEL_COLLECT = 'DEL_COLLECT'

